### PR TITLE
Fix your module

### PR DESCRIPTION
**Pull request by NitroVenom**

### CODE REVIEW

**Comment by veshrao** [comment]
@NitroVenom sax

**Comment by UsiFX** [comment]
@NitroVenom Ok

**Comment by fazar80431** [comment]
@NitroVenom pero

**Comment by veshrao** [comment]
sax bro

**Comment by veshrao** [comment]
@NitroVenom why so pero? teach me how to make modules when?

**Comment by UsiFX** [comment]
@veshrao Soon af

**Comment by veshrao** [comment]
@UsiFX

**Comment by ImSpiDy** [comment]
@veshrao

**Comment by veshrao** [comment]
@ImSpiDy

**Comment by UsiFX** [comment]
@veshrao Ummm

**Comment by veshrao** [comment]
@UsiFX me ded sur

**Comment by akirasupr** [comment]
@NitroVenom hi behen

**Pull request merged**
