### PR TITLE
Improve your mod

### PR DESCRIPTION
**Pull request by NitroVenom**

### CODE REVIEW

**Comment by UsiFX** [comment]
@NitroVenom Lol

**Comment by UsiFX** [comment]
@NitroVenom Ok

**Comment by NitroVenom** [comment]
Wen merge

**Comment by UsiFX** [comment]
@NitroVenom After my lessons.

**Comment by veshrao** [comment]
69

**Comment by UsiFX** [comment]
@veshrao Ok

**Comment by ImSpiDy** [comment]
@UsiFX Ok

**Comment by veshrao** [comment]
69  Ok's in a day

**Comment by veshrao** [comment]
sur @UsiFX when you gonna merge @NitroVenom's pr?

**Review by UsiFX — CHANGES_REQUESTED** [review]
Screenshot_2021-09-30-01-08-53

Some updater-script codes are missing so the module wont be load propably

**Review by UsiFX — COMMENTED** [review]
Screenshot_2021-09-30-01-08-53

@NitroVenom 
updater-script custom loader and others are missing and seems that will not make it load probably.

**Pull request closed without merging**
