### PR TITLE
updated readme pero dev sur

### PR DESCRIPTION
**Pull request by veshrao**

### CODE REVIEW

**Comment by UsiFX** [comment]
@veshrao kkk

**Comment by veshrao** [comment]
wow usif zuckerberg

**Comment by ImSpiDy** [comment]
@veshrao K bhai

**Comment by veshrao** [comment]
> @veshrao K bhai

saxophone 69

**Comment by fazar80431** [comment]
@veshrao lizard

**Comment by ImSpiDy** [comment]
@veshrao No bhai

**Comment by fazar80431** [comment]
@veshrao sex 😏

**Comment by veshrao** [comment]
@fazar80431 go away

**Comment by fazar80431** [comment]
@veshrao why not?

**Comment by fazar80431** [comment]
@fazar80431 i go away

**Comment by veshrao** [comment]
@fazar80431 cause you sax master

**Comment by veshrao** [comment]
@fazar80431

**Comment by fazar80431** [comment]
@veshrao i go to miui

**Comment by veshrao** [comment]
@veshrao usif gates

**Comment by fazar80431** [comment]
@veshrao Usif bezos

**Comment by veshrao** [comment]
> @veshrao Usif bezos

your head lmao

**Comment by inferno964** [comment]
:(

**Comment by fazar80431** [comment]
@veshrao X - doesn't have a factory
 ✓ - bezos

**Comment by veshrao** [comment]
> 
> 
> :(

wow pero dev arrived

**Comment by veshrao** [comment]
> 
> 
> @veshrao X - doesn't have a factory ✓ - bezos

build sax ui when?

**Pull request merged**
